
CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_TRANSACTION_TYPES START WITH 1050 INCREMENT BY 50;

CREATE TABLE KKF.TRANSACTION_TYPES
(
    ID                    BIGINT                 NOT NULL,
    NAME                  CHARACTER VARYING(128) NOT NULL,
    TYPE                  CHARACTER VARYING(128),
    ARCHIVAL              BOOLEAN,

    ROW_OBJECT_VERSION    BIGINT,
    ROW_CREATION_DATE     TIMESTAMP(3),
    ROW_CREATION_USER     CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE TIMESTAMP(3),
    ROW_MODIFICATION_USER CHARACTER VARYING(128),

    CONSTRAINT PK_TRANSACTION_TYPE PRIMARY KEY (ID)
);

COMMENT ON TABLE KKF.TRANSACTION_TYPES IS 'Rodzaje transakcji';

COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.TYPE IS 'Typ';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_TYPES.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_TRANSACTION_TYPES_NAME ON KKF.TRANSACTION_TYPES (NAME);
CREATE INDEX IDX_TRANSACTION_TYPES_TYPE ON KKF.TRANSACTION_TYPES (TYPE);