CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_TRANSACTION_SERVICES START WITH 1050 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS KKF.TRANSACTION_SERVICES
(
    ID                          BIGINT                 NOT NULL,
    NAME                        CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION                 CHARACTER VARYING(128),
    DISCOUNT                    DECIMAL(6, 2)          NOT NULL,
    NET_PRICE                   DECIMAL(6, 2)          NOT NULL,
    GROSS_PRICE                 DECIMAL(6, 2)          NOT NULL,
    VAT                         DECIMAL(6, 2)          NOT NULL,
    UNIT                        CHARACTER VARYING(128) NOT NULL,
    QUANTITY                    INTEGER                NOT NULL,
    TRANSACTION_SERVICE_TYPE_ID BIGINT                 NOT NULL,
    ARCHIVAL                    BOOLEAN,

    ROW_OBJECT_VERSION          BIGINT,
    ROW_CREATION_DATE           TIMESTAMP(3),
    ROW_CREATION_USER           CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE       TIMESTAMP(3),
    ROW_MODIFICATION_USER       CHARACTER VARYING(128),

    CONSTRAINT PK_TRANSACTION_SERVICES PRIMARY KEY (ID)
);

ALTER TABLE KKF.TRANSACTION_SERVICES
    ADD CONSTRAINT FK_TRANSACTION_SERVICES_TRANSACTION_SERVICE_TYPE_ID
        FOREIGN KEY (TRANSACTION_SERVICE_TYPE_ID) REFERENCES KKF.TRANSACTION_SERVICE_TYPES (ID);

COMMENT ON TABLE KKF.TRANSACTION_SERVICES IS 'Usługi związane z transakcjami dla rozliczeń';

COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.DISCOUNT IS 'Rabat';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.NET_PRICE IS 'Cena netto';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.GROSS_PRICE IS 'Cena brutto';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.VAT IS 'VAT';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.UNIT IS 'Jednostka';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.QUANTITY IS 'Ilość';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.TRANSACTION_SERVICE_TYPE_ID IS 'Identyfikator typu usługi';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_TRANSACTION_SERVICES_TRANSACTION_SERVICE_TYPES ON KKF.TRANSACTION_SERVICES (TRANSACTION_SERVICE_TYPE_ID);