CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_TRANSACTION_SERVICES_FOR_BILLINGS START WITH 1050 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS KKF.TRANSACTION_SERVICES_FOR_BILLINGS
(
    ID                          BIGINT                 NOT NULL,
    DTYPE                       CHARACTER VARYING(50)  NOT NULL,
    NAME                        CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION                 CHARACTER VARYING(128),
    DISCOUNT                    DECIMAL(6, 2)          NOT NULL,
    NET_PRICE                   DECIMAL(6, 2)          NOT NULL,
    GROSS_PRICE                 DECIMAL(6, 2)          NOT NULL,
    VAT                         DECIMAL(6, 2)          NOT NULL,
    UNIT                        CHARACTER VARYING(128) NOT NULL,
    QUANTITY                    INTEGER                NOT NULL,
    TRANSACTION_SERVICE_TYPE_ID BIGINT                 NOT NULL,
    ARCHIVAL                    BOOLEAN,
    REVENUE_ID                  BIGINT,
    EXPENSE_ID                  BIGINT,

    ROW_OBJECT_VERSION          BIGINT,
    ROW_CREATION_DATE           TIMESTAMP(3),
    ROW_CREATION_USER           CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE       TIMESTAMP(3),
    ROW_MODIFICATION_USER       CHARACTER VARYING(128),

    CONSTRAINT PK_TRANSACTION_SERVICES_FOR_BILLINGS PRIMARY KEY (ID)
);

ALTER TABLE KKF.TRANSACTION_SERVICES_FOR_BILLINGS
    ADD CONSTRAINT FK_TRANSACTION_SERVICES_FOR_BILLINGS_TST_ID
        FOREIGN KEY (TRANSACTION_SERVICE_TYPE_ID) REFERENCES KKF.TRANSACTION_SERVICE_TYPES (ID);
ALTER TABLE KKF.TRANSACTION_SERVICES_FOR_BILLINGS
    ADD CONSTRAINT FK_TRANSACTION_SERVICES_FOR_BILLINGS_REVENUE_ID
        FOREIGN KEY (REVENUE_ID) REFERENCES KKF.REVENUES (ID);
ALTER TABLE KKF.TRANSACTION_SERVICES_FOR_BILLINGS
    ADD CONSTRAINT FK_TRANSACTION_SERVICES_FOR_BILLINGS_EXPENSE_ID
        FOREIGN KEY (EXPENSE_ID) REFERENCES KKF.EXPENSES (ID);

COMMENT ON TABLE KKF.TRANSACTION_SERVICES_FOR_BILLINGS IS 'Usługi związane z transakcjami dla rozliczeń';

COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.DISCOUNT IS 'Rabat';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.NET_PRICE IS 'Cena netto';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.GROSS_PRICE IS 'Cena brutto';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.VAT IS 'VAT';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.UNIT IS 'Jednostka';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.QUANTITY IS 'Ilość';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.TRANSACTION_SERVICE_TYPE_ID IS 'Identyfikator typu usługi';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.DTYPE IS 'Typ';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.REVENUE_ID IS 'Identyfikator przychodu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.EXPENSE_ID IS 'Identyfikator wydatku';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICES_FOR_BILLINGS.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_TRANSACTION_SERVICES_FOR_BILLINGS_TRANSACTION_SERVICE_TYPES ON KKF.TRANSACTION_SERVICES_FOR_BILLINGS (TRANSACTION_SERVICE_TYPE_ID);
CREATE INDEX IDX_TRANSACTION_SERVICES_FOR_BILLINGS_REVENUE_ID ON KKF.TRANSACTION_SERVICES_FOR_BILLINGS (REVENUE_ID);
CREATE INDEX IDX_TRANSACTION_SERVICES_FOR_BILLINGS_EXPENSE_ID ON KKF.TRANSACTION_SERVICES_FOR_BILLINGS (EXPENSE_ID);