
CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_REVENUES START WITH 1050 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS KKF.REVENUES
(
    ID                    BIGINT                 NOT NULL,
    NAME                  CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION           CHARACTER VARYING(128),
    DELETED               BOOLEAN                NOT NULL,
    SALE_DATE             DATE                   NOT NULL,
    TOTAL_NET_PRICE       DECIMAL(6, 2),
    TOTAL_GROSS_PRICE     DECIMAL(6, 2),
    TRANSACTION_TYPE_ID   BIGINT                 NOT NULL,
    CONTRACTOR_ID         BIGINT,

    ROW_OBJECT_VERSION    BIGINT,
    ROW_CREATION_DATE     TIMESTAMP(3),
    ROW_CREATION_USER     CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE TIMESTAMP(3),
    ROW_MODIFICATION_USER CHARACTER VARYING(128),

    CONSTRAINT PK_REVENUE PRIMARY KEY (ID)
);

ALTER TABLE KKF.REVENUES
    ADD CONSTRAINT FK_REVENUES_TRANSACTION_TYPE_ID
        FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES KKF.TRANSACTION_TYPES (ID);
ALTER TABLE KKF.REVENUES
    ADD CONSTRAINT FK_REVENUES_CONTRACTOR_ID
        FOREIGN KEY (CONTRACTOR_ID) REFERENCES KKF.CONTRACTORS (ID);

COMMENT ON TABLE KKF.REVENUES IS 'Przychody';

COMMENT ON COLUMN KKF.REVENUES.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.REVENUES.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.REVENUES.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.REVENUES.DELETED IS 'Wskaźnik czy usunięto';
COMMENT ON COLUMN KKF.REVENUES.SALE_DATE IS 'Data sprzedaży';
COMMENT ON COLUMN KKF.REVENUES.TOTAL_NET_PRICE IS 'Sumaryczna cena netto';
COMMENT ON COLUMN KKF.REVENUES.TOTAL_GROSS_PRICE IS 'Sumaryczna cena brutto';
COMMENT ON COLUMN KKF.REVENUES.TRANSACTION_TYPE_ID IS 'Identyfikator rodzaju transakcji';
COMMENT ON COLUMN KKF.REVENUES.CONTRACTOR_ID IS 'Identyfikator kontrahenta';
COMMENT ON COLUMN KKF.REVENUES.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.REVENUES.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.REVENUES.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.REVENUES.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.REVENUES.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_REVENUES_NAME ON KKF.REVENUES (NAME);
CREATE INDEX IDX_REVENUES_SALE_DATE ON KKF.REVENUES (SALE_DATE);
CREATE INDEX IDX_REVENUES_TRANSACTION_TYPE_ID ON KKF.REVENUES (TRANSACTION_TYPE_ID);
CREATE INDEX IDX_REVENUES_CONTRACTOR_ID ON KKF.REVENUES (CONTRACTOR_ID);