
CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_TRANSACTION_SERVICE_TYPES START WITH 1050 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS KKF.TRANSACTION_SERVICE_TYPES
(
    ID                    BIGINT                 NOT NULL,
    NAME                  CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION           CHARACTER VARYING(128),
    ARCHIVAL              BOOLEAN                NOT NULL,

    ROW_OBJECT_VERSION    BIGINT,
    ROW_CREATION_DATE     TIMESTAMP(3),
    ROW_CREATION_USER     CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE TIMESTAMP(3),
    ROW_MODIFICATION_USER CHARACTER VARYING(128),

    CONSTRAINT PK_TRANSACTION_SERVICE_TYPE PRIMARY KEY (ID)
);

COMMENT ON TABLE KKF.TRANSACTION_SERVICE_TYPES IS 'Typy usług transakcyjnych';

COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_SERVICE_TYPES.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_TRANSACTION_SERVICE_TYPES_NAME ON KKF.TRANSACTION_SERVICE_TYPES (NAME);