CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_TRANSACTION_POSITIONS START WITH 1050 INCREMENT BY 50;

CREATE TABLE KKF.TRANSACTION_POSITIONS
(
    ID                          BIGINT                 NOT NULL,
    DTYPE                       CHARACTER VARYING(50)  NOT NULL,
    NAME                        CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION                 CHARACTER VARYING(128),
    DISCOUNT                    DECIMAL(6, 2)          NOT NULL,
    NET_PRICE                   DECIMAL(6, 2)          NOT NULL,
    GROSS_PRICE                 DECIMAL(6, 2)          NOT NULL,
    VAT                         DECIMAL(6, 2)          NOT NULL,
    UNIT                        CHARACTER VARYING(128) NOT NULL,
    QUANTITY                    INTEGER                NOT NULL,
    TRANSACTION_SERVICE_TYPE_ID BIGINT                 NOT NULL,
    ARCHIVAL                    BOOLEAN,
    REVENUE_ID                  BIGINT,
    EXPENSE_ID                  BIGINT,

    ROW_OBJECT_VERSION          BIGINT,
    ROW_CREATION_DATE           TIMESTAMP(3),
    ROW_CREATION_USER           CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE       TIMESTAMP(3),
    ROW_MODIFICATION_USER       CHARACTER VARYING(128),

    CONSTRAINT PK_TRANSACTION_POSITIONS PRIMARY KEY (ID)
);

ALTER TABLE KKF.TRANSACTION_POSITIONS
    ADD CONSTRAINT FK_TRANSACTION_POSITIONS_TST_ID
        FOREIGN KEY (TRANSACTION_SERVICE_TYPE_ID) REFERENCES KKF.TRANSACTION_SERVICE_TYPES (ID);
ALTER TABLE KKF.TRANSACTION_POSITIONS
    ADD CONSTRAINT FK_TRANSACTION_POSITIONS_REVENUE_ID
        FOREIGN KEY (REVENUE_ID) REFERENCES KKF.REVENUES (ID);
ALTER TABLE KKF.TRANSACTION_POSITIONS
    ADD CONSTRAINT FK_TRANSACTION_POSITIONS_EXPENSE_ID
        FOREIGN KEY (EXPENSE_ID) REFERENCES KKF.EXPENSES (ID);

COMMENT ON TABLE KKF.TRANSACTION_POSITIONS IS 'Usługi związane z transakcjami dla rozliczeń';

COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.DISCOUNT IS 'Rabat';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.NET_PRICE IS 'Cena netto';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.GROSS_PRICE IS 'Cena brutto';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.VAT IS 'VAT';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.UNIT IS 'Jednostka';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.QUANTITY IS 'Ilość';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.TRANSACTION_SERVICE_TYPE_ID IS 'Identyfikator typu usługi';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.DTYPE IS 'Typ';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.REVENUE_ID IS 'Identyfikator przychodu';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.EXPENSE_ID IS 'Identyfikator wydatku';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.TRANSACTION_POSITIONS.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_TRANSACTION_POSITIONS_TRANSACTION_SERVICE_TYPES ON KKF.TRANSACTION_POSITIONS (TRANSACTION_SERVICE_TYPE_ID);
CREATE INDEX IDX_TRANSACTION_POSITIONS_REVENUE_ID ON KKF.TRANSACTION_POSITIONS (REVENUE_ID);
CREATE INDEX IDX_TRANSACTION_POSITIONS_EXPENSE_ID ON KKF.TRANSACTION_POSITIONS (EXPENSE_ID);