CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_EXPENSES START WITH 1050 INCREMENT BY 50;

CREATE TABLE KKF.EXPENSES
(
    ID                    BIGINT                 NOT NULL,
    NAME                  CHARACTER VARYING(128) NOT NULL,
    DESCRIPTION           CHARACTER VARYING(128),
    DELETED               BOOLEAN                NOT NULL,
    PURCHASE_DATE         DATE                   NOT NULL,
    TOTAL_NET_PRICE       DECIMAL(6, 2),
    TOTAL_GROSS_PRICE     DECIMAL(6, 2),
    TRANSACTION_TYPE_ID   BIGINT                 NOT NULL,
    CONTRACTOR_ID         BIGINT,

    ROW_OBJECT_VERSION    BIGINT,
    ROW_CREATION_DATE     TIMESTAMP(3),
    ROW_CREATION_USER     CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE TIMESTAMP(3),
    ROW_MODIFICATION_USER CHARACTER VARYING(128),

    CONSTRAINT PK_EXPENSE PRIMARY KEY (ID)
);

ALTER TABLE KKF.EXPENSES
    ADD CONSTRAINT FK_EXPENSES_TRANSACTION_TYPE_ID
        FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES KKF.TRANSACTION_TYPES (ID);
ALTER TABLE KKF.EXPENSES
    ADD CONSTRAINT FK_EXPENSES_CONTRACTOR_ID
        FOREIGN KEY (CONTRACTOR_ID) REFERENCES KKF.CONTRACTORS (ID);

COMMENT ON TABLE KKF.EXPENSES IS 'Wydatki/rozchody';

COMMENT ON COLUMN KKF.EXPENSES.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.EXPENSES.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.EXPENSES.DELETED IS 'Wskaźnik czy usunięto';
COMMENT ON COLUMN KKF.EXPENSES.PURCHASE_DATE IS 'Data zakupu';
COMMENT ON COLUMN KKF.EXPENSES.TOTAL_NET_PRICE IS 'Sumaryczna cena netto';
COMMENT ON COLUMN KKF.EXPENSES.TOTAL_GROSS_PRICE IS 'Sumaryczna cena brutto';
COMMENT ON COLUMN KKF.EXPENSES.TRANSACTION_TYPE_ID IS 'Identyfikator rodzaju transakcji';
COMMENT ON COLUMN KKF.EXPENSES.CONTRACTOR_ID IS 'Identyfikator kontrahenta';
COMMENT ON COLUMN KKF.EXPENSES.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.EXPENSES.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.EXPENSES.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.EXPENSES.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.EXPENSES.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';


CREATE INDEX IDX_EXPENSES_NAME ON KKF.EXPENSES (NAME);
CREATE INDEX IDX_EXPENSES_SALE_DATE ON KKF.EXPENSES (PURCHASE_DATE);
CREATE INDEX IDX_EXPENSES_TRANSACTION_TYPE_ID ON KKF.EXPENSES (TRANSACTION_TYPE_ID);
CREATE INDEX IDX_EXPENSES_CONTRACTOR_ID ON KKF.EXPENSES (CONTRACTOR_ID);
