CREATE SEQUENCE IF NOT EXISTS KKF.SEQ_CONTRACTORS START WITH 1050 INCREMENT BY 50;

CREATE TABLE KKF.CONTRACTORS
(
    ID                    BIGINT                 NOT NULL,
    NAME                  CHARACTER VARYING(128),
    FIRST_NAME            CHARACTER VARYING(128),
    LAST_NAME             CHARACTER VARYING(128),
    DESCRIPTION           CHARACTER VARYING(128),
    ARCHIVAL              BOOLEAN,
    NIP                   CHARACTER VARYING(128),
    EMAIL                 CHARACTER VARYING(128),
    PHONE_NUMBER          CHARACTER VARYING(128),
    BANK_NUMBER_ACCOUNT   CHARACTER VARYING(128),
    BANK_NAME             CHARACTER VARYING(128),
    FAX                   CHARACTER VARYING(128),
    SWIFT                 CHARACTER VARYING(128),
    CONTRACTOR_TYPE       CHARACTER VARYING(128) NOT NULL,
    ADDRESS_ID            BIGINT,

    ROW_OBJECT_VERSION    BIGINT,
    ROW_CREATION_DATE     TIMESTAMP(3),
    ROW_CREATION_USER     CHARACTER VARYING(128),
    ROW_MODIFICATION_DATE TIMESTAMP(3),
    ROW_MODIFICATION_USER CHARACTER VARYING(128),

    CONSTRAINT PK_CONTRACTOR PRIMARY KEY (ID)
);

ALTER TABLE KKF.CONTRACTORS
    ADD CONSTRAINT FK_CONTRACTORS_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES KKF.ADDRESSES (ID);

COMMENT ON TABLE KKF.CONTRACTORS IS 'Kontrahenci';

COMMENT ON COLUMN KKF.CONTRACTORS.ID IS 'Klucz główny';
COMMENT ON COLUMN KKF.CONTRACTORS.NAME IS 'Nazwa';
COMMENT ON COLUMN KKF.CONTRACTORS.FIRST_NAME IS 'Imię';
COMMENT ON COLUMN KKF.CONTRACTORS.LAST_NAME IS 'Nazwisko';
COMMENT ON COLUMN KKF.CONTRACTORS.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN KKF.CONTRACTORS.ARCHIVAL IS 'Archiwalny';
COMMENT ON COLUMN KKF.CONTRACTORS.NIP IS 'NIP';
COMMENT ON COLUMN KKF.CONTRACTORS.EMAIL IS 'Email';
COMMENT ON COLUMN KKF.CONTRACTORS.PHONE_NUMBER IS 'Numer telefonu';
COMMENT ON COLUMN KKF.CONTRACTORS.BANK_NUMBER_ACCOUNT IS 'Numer konta bankowego';
COMMENT ON COLUMN KKF.CONTRACTORS.BANK_NAME IS 'Nazwa banku';
COMMENT ON COLUMN KKF.CONTRACTORS.FAX IS 'Numer faksu';
COMMENT ON COLUMN KKF.CONTRACTORS.SWIFT IS 'SWIFT';
COMMENT ON COLUMN KKF.CONTRACTORS.CONTRACTOR_TYPE IS 'Typ kontrahenta';
COMMENT ON COLUMN KKF.CONTRACTORS.ADDRESS_ID IS 'Identyfikator adresu';
COMMENT ON COLUMN KKF.CONTRACTORS.ROW_OBJECT_VERSION IS 'Pole wskazujące na wersje rekordu i do blokowania zmian';
COMMENT ON COLUMN KKF.CONTRACTORS.ROW_CREATION_DATE IS 'Data z czasem utworzenia rekordu';
COMMENT ON COLUMN KKF.CONTRACTORS.ROW_CREATION_USER IS 'Użytkownik, który utworzył rekord';
COMMENT ON COLUMN KKF.CONTRACTORS.ROW_MODIFICATION_DATE IS 'Data z czasem modyfikacji rekordu';
COMMENT ON COLUMN KKF.CONTRACTORS.ROW_MODIFICATION_USER IS 'Uzytkownik, który zmodyfikował rekord';

CREATE INDEX IDX_CONTRACTORS_NAME ON KKF.CONTRACTORS (NAME);
CREATE INDEX IDX_CONTRACTORS_NIP ON KKF.CONTRACTORS (NIP);
CREATE INDEX IDX_CONTRACTORS_ADDRESS_ID ON KKF.CONTRACTORS (ADDRESS_ID);
CREATE INDEX IDX_CONTRACTORS_CONTRACTOR_TYPE ON KKF.CONTRACTORS (CONTRACTOR_TYPE);